# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import green_ctx.proto.gpu_service_pb2 as gpu__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gpu_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GPUServiceStub(object):
    """Service definition for GPU multiplexer
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/green_ctx.proto.GPUService/HealthCheck',
                request_serializer=gpu__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=gpu__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.RequestExclusiveSMs = channel.unary_unary(
                '/green_ctx.proto.GPUService/RequestExclusiveSMs',
                request_serializer=gpu__service__pb2.RequestSMsRequest.SerializeToString,
                response_deserializer=gpu__service__pb2.RequestSMsResponse.FromString,
                _registered_method=True)
        self.FreeSMs = channel.unary_unary(
                '/green_ctx.proto.GPUService/FreeSMs',
                request_serializer=gpu__service__pb2.FreeSMsRequest.SerializeToString,
                response_deserializer=gpu__service__pb2.FreeSMsResponse.FromString,
                _registered_method=True)
        self.AllocTensor = channel.unary_unary(
                '/green_ctx.proto.GPUService/AllocTensor',
                request_serializer=gpu__service__pb2.AllocTensorRequest.SerializeToString,
                response_deserializer=gpu__service__pb2.TensorInfo.FromString,
                _registered_method=True)
        self.FreeTensor = channel.unary_unary(
                '/green_ctx.proto.GPUService/FreeTensor',
                request_serializer=gpu__service__pb2.FreeTensorRequest.SerializeToString,
                response_deserializer=gpu__service__pb2.FreeTensorResponse.FromString,
                _registered_method=True)
        self.GetTensor = channel.unary_unary(
                '/green_ctx.proto.GPUService/GetTensor',
                request_serializer=gpu__service__pb2.GetTensorRequest.SerializeToString,
                response_deserializer=gpu__service__pb2.TensorInfo.FromString,
                _registered_method=True)
        self.ExistTensor = channel.unary_unary(
                '/green_ctx.proto.GPUService/ExistTensor',
                request_serializer=gpu__service__pb2.ExistTensorRequest.SerializeToString,
                response_deserializer=gpu__service__pb2.ExistTensorResponse.FromString,
                _registered_method=True)
        self.LockTensor = channel.unary_unary(
                '/green_ctx.proto.GPUService/LockTensor',
                request_serializer=gpu__service__pb2.LockTensorRequest.SerializeToString,
                response_deserializer=gpu__service__pb2.LockTensorResponse.FromString,
                _registered_method=True)
        self.UnlockTensor = channel.unary_unary(
                '/green_ctx.proto.GPUService/UnlockTensor',
                request_serializer=gpu__service__pb2.UnlockTensorRequest.SerializeToString,
                response_deserializer=gpu__service__pb2.UnlockTensorResponse.FromString,
                _registered_method=True)
        self.KVPoolInit = channel.unary_unary(
                '/green_ctx.proto.GPUService/KVPoolInit',
                request_serializer=gpu__service__pb2.KVPoolInitRequest.SerializeToString,
                response_deserializer=gpu__service__pb2.KVPoolInitResponse.FromString,
                _registered_method=True)
        self.KVPoolAlloc = channel.unary_unary(
                '/green_ctx.proto.GPUService/KVPoolAlloc',
                request_serializer=gpu__service__pb2.KVPoolAllocRequest.SerializeToString,
                response_deserializer=gpu__service__pb2.KVPoolAllocResponse.FromString,
                _registered_method=True)
        self.KVPoolFree = channel.unary_unary(
                '/green_ctx.proto.GPUService/KVPoolFree',
                request_serializer=gpu__service__pb2.KVPoolFreeRequest.SerializeToString,
                response_deserializer=gpu__service__pb2.KVPoolFreeResponse.FromString,
                _registered_method=True)
        self.ReportRequestRate = channel.unary_unary(
                '/green_ctx.proto.GPUService/ReportRequestRate',
                request_serializer=gpu__service__pb2.UpdateRequest.SerializeToString,
                response_deserializer=gpu__service__pb2.RequestRateResponse.FromString,
                _registered_method=True)


class GPUServiceServicer(object):
    """Service definition for GPU multiplexer
    """

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestExclusiveSMs(self, request, context):
        """SM management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FreeSMs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllocTensor(self, request, context):
        """Tensor management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FreeTensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExistTensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LockTensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlockTensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KVPoolInit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KVPoolAlloc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KVPoolFree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportRequestRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GPUServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=gpu__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=gpu__service__pb2.HealthCheckResponse.SerializeToString,
            ),
            'RequestExclusiveSMs': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestExclusiveSMs,
                    request_deserializer=gpu__service__pb2.RequestSMsRequest.FromString,
                    response_serializer=gpu__service__pb2.RequestSMsResponse.SerializeToString,
            ),
            'FreeSMs': grpc.unary_unary_rpc_method_handler(
                    servicer.FreeSMs,
                    request_deserializer=gpu__service__pb2.FreeSMsRequest.FromString,
                    response_serializer=gpu__service__pb2.FreeSMsResponse.SerializeToString,
            ),
            'AllocTensor': grpc.unary_unary_rpc_method_handler(
                    servicer.AllocTensor,
                    request_deserializer=gpu__service__pb2.AllocTensorRequest.FromString,
                    response_serializer=gpu__service__pb2.TensorInfo.SerializeToString,
            ),
            'FreeTensor': grpc.unary_unary_rpc_method_handler(
                    servicer.FreeTensor,
                    request_deserializer=gpu__service__pb2.FreeTensorRequest.FromString,
                    response_serializer=gpu__service__pb2.FreeTensorResponse.SerializeToString,
            ),
            'GetTensor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTensor,
                    request_deserializer=gpu__service__pb2.GetTensorRequest.FromString,
                    response_serializer=gpu__service__pb2.TensorInfo.SerializeToString,
            ),
            'ExistTensor': grpc.unary_unary_rpc_method_handler(
                    servicer.ExistTensor,
                    request_deserializer=gpu__service__pb2.ExistTensorRequest.FromString,
                    response_serializer=gpu__service__pb2.ExistTensorResponse.SerializeToString,
            ),
            'LockTensor': grpc.unary_unary_rpc_method_handler(
                    servicer.LockTensor,
                    request_deserializer=gpu__service__pb2.LockTensorRequest.FromString,
                    response_serializer=gpu__service__pb2.LockTensorResponse.SerializeToString,
            ),
            'UnlockTensor': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlockTensor,
                    request_deserializer=gpu__service__pb2.UnlockTensorRequest.FromString,
                    response_serializer=gpu__service__pb2.UnlockTensorResponse.SerializeToString,
            ),
            'KVPoolInit': grpc.unary_unary_rpc_method_handler(
                    servicer.KVPoolInit,
                    request_deserializer=gpu__service__pb2.KVPoolInitRequest.FromString,
                    response_serializer=gpu__service__pb2.KVPoolInitResponse.SerializeToString,
            ),
            'KVPoolAlloc': grpc.unary_unary_rpc_method_handler(
                    servicer.KVPoolAlloc,
                    request_deserializer=gpu__service__pb2.KVPoolAllocRequest.FromString,
                    response_serializer=gpu__service__pb2.KVPoolAllocResponse.SerializeToString,
            ),
            'KVPoolFree': grpc.unary_unary_rpc_method_handler(
                    servicer.KVPoolFree,
                    request_deserializer=gpu__service__pb2.KVPoolFreeRequest.FromString,
                    response_serializer=gpu__service__pb2.KVPoolFreeResponse.SerializeToString,
            ),
            'ReportRequestRate': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportRequestRate,
                    request_deserializer=gpu__service__pb2.UpdateRequest.FromString,
                    response_serializer=gpu__service__pb2.RequestRateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'green_ctx.proto.GPUService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('green_ctx.proto.GPUService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GPUService(object):
    """Service definition for GPU multiplexer
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/green_ctx.proto.GPUService/HealthCheck',
            gpu__service__pb2.HealthCheckRequest.SerializeToString,
            gpu__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestExclusiveSMs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/green_ctx.proto.GPUService/RequestExclusiveSMs',
            gpu__service__pb2.RequestSMsRequest.SerializeToString,
            gpu__service__pb2.RequestSMsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FreeSMs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/green_ctx.proto.GPUService/FreeSMs',
            gpu__service__pb2.FreeSMsRequest.SerializeToString,
            gpu__service__pb2.FreeSMsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllocTensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/green_ctx.proto.GPUService/AllocTensor',
            gpu__service__pb2.AllocTensorRequest.SerializeToString,
            gpu__service__pb2.TensorInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FreeTensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/green_ctx.proto.GPUService/FreeTensor',
            gpu__service__pb2.FreeTensorRequest.SerializeToString,
            gpu__service__pb2.FreeTensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/green_ctx.proto.GPUService/GetTensor',
            gpu__service__pb2.GetTensorRequest.SerializeToString,
            gpu__service__pb2.TensorInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExistTensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/green_ctx.proto.GPUService/ExistTensor',
            gpu__service__pb2.ExistTensorRequest.SerializeToString,
            gpu__service__pb2.ExistTensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LockTensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/green_ctx.proto.GPUService/LockTensor',
            gpu__service__pb2.LockTensorRequest.SerializeToString,
            gpu__service__pb2.LockTensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlockTensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/green_ctx.proto.GPUService/UnlockTensor',
            gpu__service__pb2.UnlockTensorRequest.SerializeToString,
            gpu__service__pb2.UnlockTensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KVPoolInit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/green_ctx.proto.GPUService/KVPoolInit',
            gpu__service__pb2.KVPoolInitRequest.SerializeToString,
            gpu__service__pb2.KVPoolInitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KVPoolAlloc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/green_ctx.proto.GPUService/KVPoolAlloc',
            gpu__service__pb2.KVPoolAllocRequest.SerializeToString,
            gpu__service__pb2.KVPoolAllocResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KVPoolFree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/green_ctx.proto.GPUService/KVPoolFree',
            gpu__service__pb2.KVPoolFreeRequest.SerializeToString,
            gpu__service__pb2.KVPoolFreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportRequestRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/green_ctx.proto.GPUService/ReportRequestRate',
            gpu__service__pb2.UpdateRequest.SerializeToString,
            gpu__service__pb2.RequestRateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
